import type { ArchEdge, ArchNode } from '../types';
import {
  buildDependencyMap,
  buildUniqueNames,
  isExternalClientType,
  isSupportedAwsType,
  isUnsupportedNonAwsType,
  toLogicalId,
  toYaml,
} from './iacUtils';

export function generateCloudFormation(nodes: ArchNode[], edges: ArchEdge[], projectName: string): string {
  const activeNodes = nodes.filter(node => node.data.componentType !== 'groupNode');
  const names = buildUniqueNames(activeNodes);
  const dependencies = buildDependencyMap(edges);
  const logicalIds = new Map<string, string>();

  for (const node of activeNodes) {
    logicalIds.set(node.id, toLogicalId(names.get(node.id) ?? node.data.label));
  }

  const resources: Record<string, Record<string, unknown>> = {
    Vpc: {
      Type: 'AWS::EC2::VPC',
      Properties: {
        CidrBlock: { Ref: 'VpcCidr' },
        EnableDnsHostnames: true,
        EnableDnsSupport: true,
      },
    },
    PublicSubnet1: {
      Type: 'AWS::EC2::Subnet',
      Properties: {
        VpcId: { Ref: 'Vpc' },
        CidrBlock: { 'Fn::Select': [0, { Ref: 'PublicSubnetCidrs' }] },
        MapPublicIpOnLaunch: true,
      },
    },
    PrivateSubnet1: {
      Type: 'AWS::EC2::Subnet',
      Properties: {
        VpcId: { Ref: 'Vpc' },
        CidrBlock: { 'Fn::Select': [0, { Ref: 'PrivateSubnetCidrs' }] },
      },
    },
  };

  for (const node of activeNodes) {
    const type = node.data.componentType;
    if (isUnsupportedNonAwsType(type) || isExternalClientType(type) || !isSupportedAwsType(type)) {
      continue;
    }

    const logicalId = logicalIds.get(node.id) ?? toLogicalId(node.data.label);
    const resource = renderCfnResource(node, logicalId);
    if (!resource) {
      continue;
    }

    const upstream = (dependencies.get(node.id) ?? [])
      .map(sourceId => logicalIds.get(sourceId))
      .filter((value): value is string => Boolean(value));

    if (upstream.length === 1) {
      resource.DependsOn = upstream[0];
    } else if (upstream.length > 1) {
      resource.DependsOn = upstream;
    }

    resources[logicalId] = resource;
  }

  const template = {
    AWSTemplateFormatVersion: '2010-09-09',
    Description: `CloudFormation template for ${projectName} generated by ArchViz`,
    Parameters: buildParameters(activeNodes),
    Resources: resources,
    Outputs: buildOutputs(activeNodes, logicalIds),
  };

  return toYaml(template);
}

function buildParameters(nodes: ArchNode[]): Record<string, unknown> {
  const parameters: Record<string, unknown> = {
    ProjectName: { Type: 'String', Default: 'archviz' },
    AwsRegion: { Type: 'String', Default: 'us-east-1' },
    EnvironmentName: { Type: 'String', Default: 'dev' },
    VpcCidr: { Type: 'String', Default: '10.0.0.0/16' },
    PublicSubnetCidrs: { Type: 'CommaDelimitedList', Default: '10.0.1.0/24' },
    PrivateSubnetCidrs: { Type: 'CommaDelimitedList', Default: '10.0.101.0/24' },
  };

  if (nodes.some(node => node.data.componentType === 'load-balancer')) {
    parameters.AlbListenerPort = { Type: 'Number', Default: 443 };
  }

  if (nodes.some(node => ['postgresql', 'mysql'].includes(node.data.componentType))) {
    parameters.DbUsername = { Type: 'String', Default: 'appuser' };
    parameters.DbPassword = { Type: 'String', NoEcho: true };
    parameters.DbPort = { Type: 'Number', Default: 5432 };
  }

  if (nodes.some(node => node.data.componentType === 'redis')) {
    parameters.RedisPort = { Type: 'Number', Default: 6379 };
  }

  for (const node of nodes) {
    if (isComputeNode(node.data.componentType) || ['postgresql', 'mysql'].includes(node.data.componentType)) {
      parameters[`${toLogicalId(node.data.label)}InstanceType`] = {
        Type: 'String',
        Default: node.data.tier.label.includes('.') ? node.data.tier.label : 't3.medium',
      };
    }
  }

  return parameters;
}

function buildOutputs(nodes: ArchNode[], logicalIds: Map<string, string>): Record<string, unknown> {
  const outputs: Record<string, unknown> = {
    VpcId: { Value: { Ref: 'Vpc' } },
    PublicSubnetIds: { Value: { Ref: 'PublicSubnet1' } },
    PrivateSubnetIds: { Value: { Ref: 'PrivateSubnet1' } },
  };

  const firstAlb = nodes.find(node => node.data.componentType === 'load-balancer');
  if (firstAlb) {
    outputs.AlbDnsName = {
      Value: { 'Fn::GetAtt': [logicalIds.get(firstAlb.id) ?? toLogicalId(firstAlb.data.label), 'DNSName'] },
    };
  }

  const firstRds = nodes.find(node => ['postgresql', 'mysql'].includes(node.data.componentType));
  if (firstRds) {
    outputs.RdsEndpoint = {
      Value: { 'Fn::GetAtt': [logicalIds.get(firstRds.id) ?? toLogicalId(firstRds.data.label), 'Endpoint.Address'] },
    };
  }

  const firstEks = nodes.find(node => node.data.componentType === 'kubernetes-cluster');
  if (firstEks) {
    const logicalId = logicalIds.get(firstEks.id) ?? toLogicalId(firstEks.data.label);
    outputs.EksClusterEndpoint = { Value: { 'Fn::GetAtt': [logicalId, 'Endpoint'] } };
    outputs.EksClusterName = { Value: { Ref: logicalId } };
  }

  const firstRedis = nodes.find(node => node.data.componentType === 'redis');
  if (firstRedis) {
    outputs.ElastiCacheEndpoint = {
      Value: { 'Fn::GetAtt': [logicalIds.get(firstRedis.id) ?? toLogicalId(firstRedis.data.label), 'RedisEndpoint.Address'] },
    };
  }

  return outputs;
}

function renderCfnResource(node: ArchNode, logicalId: string): Record<string, unknown> | null {
  const type = node.data.componentType;

  if (isComputeNode(type)) {
    return {
      Type: 'AWS::EC2::Instance',
      Properties: {
        InstanceType: { Ref: `${toLogicalId(node.data.label)}InstanceType` },
        ImageId: 'ami-1234567890abcdef0',
        SubnetId: { Ref: 'PrivateSubnet1' },
      },
    };
  }

  if (type === 'lambda') {
    return {
      Type: 'AWS::Lambda::Function',
      Properties: {
        Runtime: 'nodejs20.x',
        Handler: 'index.handler',
        Role: { 'Fn::Sub': `arn:aws:iam::\${AWS::AccountId}:role/${logicalId}LambdaRole` },
        MemorySize: parseMemory(node.data.tier.label),
        Code: { ZipFile: 'exports.handler = async () => ({ statusCode: 200, body: "ok" });' },
      },
    };
  }

  if (type === 'ecs-fargate') {
    return {
      Type: 'AWS::ECS::Service',
      Properties: {
        LaunchType: 'FARGATE',
        DesiredCount: 1,
      },
    };
  }

  if (type === 'kubernetes-cluster') {
    return {
      Type: 'AWS::EKS::Cluster',
      Properties: {
        Name: logicalId,
        ResourcesVpcConfig: {
          SubnetIds: [{ Ref: 'PublicSubnet1' }, { Ref: 'PrivateSubnet1' }],
        },
      },
    };
  }

  if (type === 'postgresql' || type === 'mysql') {
    return {
      Type: 'AWS::RDS::DBInstance',
      Properties: {
        Engine: type === 'postgresql' ? 'postgres' : 'mysql',
        DBInstanceClass: { Ref: `${toLogicalId(node.data.label)}InstanceType` },
        MasterUsername: { Ref: 'DbUsername' },
        MasterUserPassword: { Ref: 'DbPassword' },
        Port: { Ref: 'DbPort' },
        AllocatedStorage: 20,
      },
    };
  }

  if (type === 'redis') {
    return {
      Type: 'AWS::ElastiCache::CacheCluster',
      Properties: {
        Engine: 'redis',
        CacheNodeType: node.data.tier.label.startsWith('cache.') ? node.data.tier.label : 'cache.t3.micro',
        NumCacheNodes: 1,
        Port: { Ref: 'RedisPort' },
      },
    };
  }

  if (type === 's3') {
    return {
      Type: 'AWS::S3::Bucket',
      Properties: {
        BucketName: { 'Fn::Sub': `${logicalId.toLowerCase()}-\${EnvironmentName}` },
      },
    };
  }

  if (type === 'load-balancer') {
    return {
      Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
      Properties: {
        Scheme: 'internet-facing',
        Type: 'application',
        Subnets: [{ Ref: 'PublicSubnet1' }],
      },
    };
  }

  if (type === 'dynamodb') {
    return {
      Type: 'AWS::DynamoDB::Table',
      Properties: {
        BillingMode: 'PAY_PER_REQUEST',
        AttributeDefinitions: [{ AttributeName: 'id', AttributeType: 'S' }],
        KeySchema: [{ AttributeName: 'id', KeyType: 'HASH' }],
      },
    };
  }

  if (type === 'aws-cognito') {
    return {
      Type: 'AWS::Cognito::UserPool',
      Properties: {
        UserPoolName: logicalId,
      },
    };
  }

  if (type === 'cdn') {
    return {
      Type: 'AWS::CloudFront::Distribution',
      Properties: {
        DistributionConfig: {
          Enabled: true,
          DefaultCacheBehavior: {
            TargetOriginId: `${logicalId}Origin`,
            ViewerProtocolPolicy: 'redirect-to-https',
          },
          Origins: [{
            DomainName: 'example.com',
            Id: `${logicalId}Origin`,
            CustomOriginConfig: { OriginProtocolPolicy: 'https-only' },
          }],
        },
      },
    };
  }

  if (type === 'api-gateway') {
    return {
      Type: 'AWS::ApiGatewayV2::Api',
      Properties: {
        Name: logicalId,
        ProtocolType: 'HTTP',
      },
    };
  }

  if (type === 'sqs') {
    return {
      Type: 'AWS::SQS::Queue',
      Properties: {},
    };
  }

  if (type === 'sns') {
    return {
      Type: 'AWS::SNS::Topic',
      Properties: {
        TopicName: logicalId,
      },
    };
  }

  if (type === 'dns') {
    return {
      Type: 'AWS::Route53::HostedZone',
      Properties: {
        Name: `${logicalId.toLowerCase()}.example.com`,
      },
    };
  }

  return null;
}

function parseMemory(label: string): number {
  const match = label.match(/(\d+)/);
  return match ? Number.parseInt(match[1], 10) : 512;
}

function isComputeNode(type: string): boolean {
  return ['api-server', 'web-server', 'worker', 'websocket-server', 'graphql-server', 'game-server', 'ml-worker'].includes(type);
}
