import { toPng } from 'html-to-image';
import { jsPDF } from 'jspdf';
import type { SystemMetrics, ArchNode, ArchEdge, CloudProvider } from '../types';
import { getArbitrageCosts } from './costEngine';
import { toastBus } from '../components/ToastSystem';

export interface ReportConfig {
  nodes: ArchNode[];
  edges: ArchEdge[];
  metrics: SystemMetrics;
  projectName: string;
  isWhiteLabel: boolean;
  cloudProvider: CloudProvider;
  canvasElementId?: string;
}

export async function generateArchitectureReport({
  nodes,
  edges,
  metrics,
  projectName,
  isWhiteLabel,
  cloudProvider,
  canvasElementId = 'arch-canvas-container'
}: ReportConfig) {
  try {
    toastBus.emit('Generating High-Res Report...', 'info');
    
    // 1. Capture Canvas
    const canvasElement = document.getElementById(canvasElementId);
    if (!canvasElement) throw new Error('Canvas element not found.');

    const dataUrl = await toPng(canvasElement, {
      quality: 1,
      pixelRatio: 2,
      backgroundColor: '#0a0a0f' // Match Midnight Obsidian
    });

    // 2. Initialize PDF (A4 Portrait)
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 15;
    
    // --- PAGE 1: Canvas & Summary ---
    // Header
    pdf.setFillColor(20, 20, 25);
    pdf.rect(0, 0, pageWidth, 40, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.text(projectName, margin, 25);
    
    // Watermark
    if (!isWhiteLabel) {
      pdf.setFontSize(10);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by ArchViz Enterprise', pageWidth - margin, 25, { align: 'right' });
    }

    // Canvas Image
    pdf.setTextColor(40, 40, 40);
    pdf.setFontSize(14);
    pdf.text('Architecture Diagram', margin, 50);
    
    // Calculate aspect ratio
    const imgProps = pdf.getImageProperties(dataUrl);
    const pdfImgWidth = pageWidth - margin * 2;
    const pdfImgHeight = (imgProps.height * pdfImgWidth) / imgProps.width;
    
    pdf.addImage(dataUrl, 'PNG', margin, 55, pdfImgWidth, pdfImgHeight);

    // --- PAGE 2: Financials & Arbitrage ---
    pdf.addPage();
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(20);
    pdf.text('Architecture Assessment', margin, 25);

    pdf.setFontSize(14);
    pdf.text('Cost Arbitrage & Economics', margin, 40);

    const arb = getArbitrageCosts(nodes, edges);
    
    pdf.setFontSize(10);
    pdf.text(`AWS Projected Cost: $${arb.aws.toFixed(2)}/mo ${cloudProvider === 'aws' ? '(Selected)' : ''}`, margin, 50);
    pdf.text(`GCP Projected Cost: $${arb.gcp.toFixed(2)}/mo ${cloudProvider === 'gcp' ? '(Selected)' : ''}`, margin, 60);
    pdf.text(`Azure Projected Cost: $${arb.azure.toFixed(2)}/mo ${cloudProvider === 'azure' ? '(Selected)' : ''}`, margin, 70);

    pdf.setFontSize(14);
    pdf.text('Reliability & SLA', margin, 90);
    pdf.setFontSize(10);
    pdf.text(`Grade: ${metrics.letterGrade}`, margin, 100);
    pdf.text(`Health Score: ${metrics.healthScore}/100`, margin, 110);
    pdf.text(`Composite SLA: ${metrics.nines} (${metrics.compositeSLA.toFixed(4)}%)`, margin, 120);
    pdf.text(`Estimated Downtime: ${metrics.downtimePerYear} / year`, margin, 130);

    // --- PAGE 3: Compliance & Security ---
    if (metrics.warnings.length > 0) {
      pdf.addPage();
      pdf.setFontSize(16);
      pdf.text('Security & Warnings', margin, 25);
      
      let y = 40;
      metrics.warnings.forEach((warn) => {
        if (y > 270) { pdf.addPage(); y = 25; }
        pdf.setFontSize(10);
        pdf.setTextColor(warn.type === 'critical' ? 255 : 0, 0, 0); // Red for critical
        pdf.text(`[${warn.type.toUpperCase()}] ${warn.message}`, margin, y);
        y += 10;
        pdf.setTextColor(0, 0, 0); // Reset
      });
    }

    // Save
    pdf.save(`${projectName.replace(/ /g, '_')}_Report.pdf`);
    toastBus.emit('Report Downloaded Successfully!', 'success');

  } catch (err) {
    console.error('Report Generation Error', err);
    toastBus.emit('Failed to generate report', 'error');
  }
}
